name: CI/CD Workflow

on:
  push:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Fmt
        run: deno fmt --check ./src

      - name: Lint
        run: deno lint ./src

      - name: Test
        run: |
          deno test --coverage=./coverage ./src

      - name: Generate coverage report
        run: deno coverage --lcov ./coverage > coverage.lcov

      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov

  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish

  changelog:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Generate release
        run: npx standard-version

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
